### ISSUE TITLE
VisualizerTask bug

### ISSUE THREAD

**Issue by jawira** [phingofficial/guide#14]
Hi, I just updated to **phing-3.0.0-alpha4** and I have a bug with **VisualizerTask**.

My buildfile:

```xml
<?xml version="1.0" encoding="UTF-8" ?>

<project name="testing" default="visualizer">

    <target name="visualizer">
      <visualizer/>
    </target>

</project>
```

The output:

```console
$ phing -f demo.xml 
Buildfile: /home/jawira/PhpstormProjects/case-converter/demo.xml

testing > visualizer:


BUILD FAILED
Call to undefined method GuzzleHttp\Psr7\Response::send()
#0 phar:///usr/local/bin/phing/classes/phing/tasks/ext/visualizer/VisualizerTask.php(145): VisualizerTask->generateImage()
#1 phar:///usr/local/bin/phing/classes/phing/UnknownElement.php(112): VisualizerTask->main()
#2 [internal function]: UnknownElement->main()
#3 phar:///usr/local/bin/phing/classes/phing/dispatch/DispatchUtils.php(84): ReflectionMethod->invoke()
#4 phar:///usr/local/bin/phing/classes/phing/Task.php(186): DispatchUtils::main()
#5 phar:///usr/local/bin/phing/classes/phing/Target.php(379): Task->perform()
#6 phar:///usr/local/bin/phing/classes/phing/Target.php(409): Target->main()
#7 phar:///usr/local/bin/phing/classes/phing/Project.php(784): Target->performTasks()
#8 phar:///usr/local/bin/phing/classes/phing/Project.php(754): Project->executeTarget()
#9 phar:///usr/local/bin/phing/classes/phing/Phing.php(750): Project->executeTargets()
#10 phar:///usr/local/bin/phing/classes/phing/Phing.php(220): Phing->runBuild()
#11 phar:///usr/local/bin/phing/classes/phing/Phing.php(368): Phing::start()
#12 phar:///usr/local/bin/phing/bin/phing.php(60): Phing::fire()
#13 /usr/local/bin/phing(6): include('phar:///usr/loc...')
#14 {main}

Total time: 0.6604 seconds

Call to undefined method GuzzleHttp\Psr7\Response::send()
```

I'm more than willing to help with a PR, but I will need some pointers please.

**Comment by siad007** [comment]
My first guess is that the visualizer task uses
Response::send from guzzle which might be renamed or so in a newer version?

Jawira Portugal <notifications@github.com> schrieb am Sa. 29. Aug. 2020 um
18:38:
